name: nodejs CD...

on:
  push:
    branches:
      - master

jobs:
  continuous_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Seup up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t nodejs-test-app:latest .

      - name: Tag Docker Image
        run: docker tag nodejs-test-app:latest ${{ secrets.DOCKER_USERNAME }}/nodejs-test-app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-test-app:latest

      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH known hosts
        run: ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-test-app:latest
          sudo docker stop nodejs-test-app || true
          sudo docker rm nodejs-test-app || true
          sudo docker run -d --name nodejs-test-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/nodejs-test-app:latest
          EOF
      