name: nodejs CD...

on:
  push:
    branches:
      - master

jobs:
  continuous_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Seup up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t nodejs-test-app:latest .

      - name: Tag Docker Image
        run: docker tag nodejs-test-app:latest ${{ secrets.DOCKER_USERNAME }}/nodejs-test-app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-test-app:latest