name: nodejs CI...

on:
  pull_request:
    branches:
      - master

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install depencencies
        run: npm instal

      - name: Build application
        run: echo "Building application"

      - name: Run unit tests
        run: echo "Runing unit tests"

      - name: Run integration tests
        run: echo "Running integration tests"